/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteFileKey, RouteLayoutKey, RawRouteComponent } from "@elegant-router/types";

export const layouts: Record<RouteLayoutKey, RawRouteComponent> = {
  base: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/layouts/base/index.vue"),
  blank: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/layouts/blank/index.vue"),
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
  403: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/(builtin)/403.vue"),
  404: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/(builtin)/404.vue"),
  Demo: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/demo"),
  Home: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/home/index.vue"),
  HomeChild: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/home/child.vue"),
  HomeChild2: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/home/child2.vue"),
  List: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/list/index.vue"),
  ListAdd: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/list/add.vue"),
  ListDetail2IdUserId: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/list/detail2-[[id]]-[[userId]].vue"),
  ListDetailIdUserId: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/list/detail_[id]_[userId].vue"),
  ListEditId: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/list/edit_[id].vue"),
  ListId: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/list/[id].vue"),
  Login: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/(builtin)/login/index.vue"),
  Wip: () => import("/project/sandbox/user-workspace/frontend-soybean-vue/src/views/(builtin)/wip.vue"),
};
